name: fat_jupyter
channels:
  - conda-forge
  - defaults
dependencies:
  - backcall=0.1.0=py_0
  - backports=1.0=py27_1
  - backports.functools_lru_cache=1.5=py27_0
  - backports.shutil_get_terminal_size=1.0.0=py_3
  - backports.shutil_which=3.5.1=py27_1
  - backports_abc=0.5=py27_0
  - bleach=2.1.3=py_0
  - ca-certificates=2018.4.16=0
  - certifi=2018.4.16=py27_0
  - colorama=0.3.9=py27_0
  - configparser=3.5.0=py27_0
  - cycler=0.10.0=py27_0
  - decorator=4.3.0=py_0
  - entrypoints=0.2.3=py27_1
  - enum34=1.1.6=py27_1
  - fatiando=0.5
  - funcsigs=1.0.2=py_2
  - functools32=3.2.3.2=py27_2
  - future=0.16.0=py27_0
  - futures=3.2.0=py27_0
  - html5lib=1.0.1=py_0
  - ipykernel=4.8.2=py27_0
  - ipython=5.7.0=py27_0
  - ipython_genutils=0.2.0=py27_0
  - ipywidgets=7.2.1=py27_1
  - jedi=0.12.0=py27_0
  - jinja2=2.10=py27_0
  - jsonschema=2.6.0=py27_1
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.3=py27_0
  - jupyter_console=5.2.0=py27_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.0.1=py27_1
  - markupsafe=1.0=py27_0
  - matplotlib=2.2.2=py27_1
  - mistune=0.8.3=py27_1
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py27_0
  - notebook=5.5.0=py27_0
  - olefile=0.45.1=py27_0
  - pandocfilters=1.4.2=py27_0
  - parso=0.2.1=py_0
  - pathlib2=2.3.2=py27_0
  - pickleshare=0.7.4=py27_0
  - pillow=5.1.0=py27_0
  - pip=9.0.3=py27_0
  - prompt_toolkit=1.0.15=py27_0
  - pygments=2.2.0=py27_0
  - pyparsing=2.2.0=py27_0
  - pyqt=5.6.0=py27_5
  - python=2.7.15=0
  - python-dateutil=2.7.3=py_0
  - pytz=2018.4=py_0
  - pyzmq=17.0.0=py27_4
  - qtconsole=4.3.1=py27_0
  - scandir=1.7=py27_0
  - send2trash=1.5.0=py_0
  - setuptools=39.2.0=py27_0
  - simplegeneric=0.8.1=py27_0
  - singledispatch=3.4.0.3=py27_0
  - sip=4.18=py27_1
  - six=1.11.0=py27_1
  - terminado=0.8.1=py27_0
  - testpath=0.3.1=py27_0
  - tornado=5.0.2=py27_0
  - traitlets=4.3.2=py27_0
  - wcwidth=0.1.7=py27_0
  - wheel=0.31.0=py27_0
  - widgetsnbextension=3.2.1=py27_0

